name: deploy-prod
on:
    push:
        branches:
            - main

jobs:
    changes:
        name: Check changed projects
        runs-on: ubuntu-latest
        permissions:
            pull-requests: read
        outputs:
            web: ${{ steps.filter.outputs.web }}
            projects: ${{ steps.filter.outputs.changes }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.LEMON_BOT_TOKEN }}
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  base: 'main'
                  filters: |
                      web:
                          - 'apps/web/**'
                          - 'libs/**'
                          - '!**/*.json'
                          - '!**/*.md'

    build:
        needs: changes
        if: ${{ fromJson(needs.changes.outputs.projects)[0] != null }}
        name: Build and Set Version
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        outputs:
            web-version: ${{ steps.web-version.outputs.version }}
        steps:
            - name: Check out a copy of the repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.LEMON_BOT_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc' # node 20버전 이상

            - name: Get Yarn cache path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache Yarn cache and node_modules
              id: cache-dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      ${{ steps.yarn-cache-dir-path.outputs.dir }}
                      node_modules
                  key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-

            - name: Install dependencies
              run: |
                  yarn install --frozen-lockfile
              if: steps.cache-dependencies.outputs.cache-hit != 'true'

            - name: Configure git
              run: |
                  git config user.name "${GITHUB_ACTOR}"
                  git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

            - name: Get Latest Version of Web
              if: ${{ needs.changes.outputs.web == 'true' }}
              id: web-version
              run: |
                  VERSION=$(node -p "require('./apps/web/package.json').version")
                  echo "web@$VERSION"
                  echo "version=$VERSION" >> $GITHUB_OUTPUT

    deploy-prod:
        name: Deploy to Prod
        needs: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                project: [web]
                include:
                    - project: web
                      version: ${{ needs.build.outputs.web-version }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.LEMON_BOT_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc' # node 20버전 이상

            - name: Get Yarn cache path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache Yarn cache and node_modules
              id: cache-dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      ${{ steps.yarn-cache-dir-path.outputs.dir }}
                      node_modules
                  key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-

            - name: Install dependencies
              run: |
                  yarn install --frozen-lockfile
              if: steps.cache-dependencies.outputs.cache-hit != 'true'

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Deploy to PROD
              if: ${{ matrix.version != null }}
              run: |
                  chmod +x scripts/deploy-${{ matrix.project }}.sh
                  yarn deploy:${{ matrix.project }}:prod

#            - name: Post Web release to a Slack channel
#              if: ${{ matrix.project == 'web' && matrix.version != null }}
#              id: web-post-slack
#              uses: slackapi/slack-github-action@v1.25.0
#              with:
#                  channel-id: ${{ secrets.COLOVER_CHANNEL }}
#                  payload: |
#                      {
#                          "text": "프론트 운영 배포",
#                          "blocks": [
#                      		  {
#                                  "type": "section",
#                                  "text": {
#                                      "type": "mrkdwn",
#                                      "text": "*웹 <https://front.lemoncloud.io/|운영 서버> 배포되었습니다. v${{ matrix.version }}*"
#                                  }
#                              }
#                          ]
#                      }
#              env:
#                  SLACK_BOT_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }
#
#            - name: Post Admin release to a Slack channel
#              if: ${{ matrix.project == 'admin' && matrix.version != null }}
#              id: admin-post-slack
#              uses: slackapi/slack-github-action@v1.25.0
#              with:
#                  channel-id: ${{ secrets.COLOVER_CHANNEL }}
#                  payload: |
#                      {
#                          "text": "어드민 운영 배포",
#                          "blocks": [
#                      		  {
#                                  "type": "section",
#                                  "text": {
#                                      "type": "mrkdwn",
#                                      "text": "*어드민 <https://admin.lemoncloud.io/|운영 서버> 배포되었습니다. v${{ matrix.version }}*"
#                                  }
#                              }
#                          ]
#                      }
#              env:
#                  SLACK_BOT_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }
